stages:
  data_ingestion:
    cmd:
      - python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - data/raw

  pre_processing:
    cmd:
      - echo "Step started"
      - python src/pre_processing.py
    deps:
      - data/raw
      - src/pre_processing.py
    
    outs:
      - data/interim

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - data/interim
      - src/feature_engineering.py
    params:
      - feature_engineering.max_features
    outs:
      - data/processed

  model_training:
    cmd: python src/model_training.py
    deps:
      - data/processed
      - src/model_training.py
    params:
      - model_training.n_estimators
      - model_training.random_state
    outs:
      - models/models.pkl

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - models/models.pkl
      - src/model_evaluation.py
    outs:
      - reports/reports.json
